apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
    project: my-apps
  source:
    path: apps
    repoURL: https://github.com/Jeremy4040/argocd.git
    targetRevision: HEAD
